---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    name: mozillians-broker
  name: mozillians-broker
  namespace: mozillians-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mozillians-broker
    spec:
      containers:
      - image: redis:3
        name: mozillians-broker
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    name: mozillians-broker
  name: mozillians-broker
  namespace: mozillians-dev
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    name: mozillians-broker
