apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
  namespace: mozillians-dev
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 6379
    targetPort: 0
  selector:
    io.kompose.service: broker
status:
  loadBalancer: {}
