apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: celery
  name: celery
  namespace: mozillians-dev
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: celery
    spec:
      containers:
      - args:
        - /code/bin/run-celery.sh
        env:
        - name: C_FORCE_ROOT
          value: "true"
        image: danielhartnell/mozillians:1.0.1
        name: celery
        resources: {}
      restartPolicy: Always
      volumes:
      - name: celery-claim0
        persistentVolumeClaim:
          claimName: celery-claim0
status: {}
