apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
  namespace: mozillians-dev
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: mozillians
        - name: MYSQL_PASSWORD
          value: replace
        - name: MYSQL_ROOT_PASSWORD
          value: replace
        - name: MYSQL_USER
          value: mozillians
        image: mariadb:10.2
        name: db
        ports:
        - containerPort: 3600
        resources: {}
      restartPolicy: Always
status: {}
