---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    name: mozillians-db
  name: mozillians-db
  namespace: mozillians-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mozillians-db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: mozillians
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mozillians-db
              key: mysql_root_password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mozillians-db
              key: mysql_password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mozillians-db
              key: mysql_user
        image: mariadb:10.2
        name: mozillians-db
        ports:
        - containerPort: 3600
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    name: mozillians-db
  name: mozillians-db
  namespace: mozillians-dev
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    name: mozillians-db
