apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: flower-claim0
  name: flower-claim0
  namespace: mozillians-dev
spec:
  storageClassName: mozillians
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
