---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    name: mozillians-flower
  name: mozillians-flower
  namespace: mozillians-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mozillians-flower
    spec:
      containers:
      - name: mozillians-flower
        image: danielhartnell/mozillians:1.0.4
        command: ["flower"]
        args: ["-A", "mozillians", "--address=0.0.0.0", "--port=5555"]
        ports:
        - containerPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    name: mozillians-flower
  name: mozillians-flower
  namespace: mozillians-dev
spec:
  ports:
  - protocol: TCP
    port: 5555
    targetPort: 5555
  selector:
    name: mozillians-flower
