apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: flowersvc
  name: flowersvc
  namespace: mozillians-dev
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: flowersvc
    spec:
      containers:
      - name: flowersvc
        image: danielhartnell/mozillians:1.0.1
        command: ["flower"]
        args: ["-A", "mozillians", "--address=0.0.0.0", "--port=5555"]
        ports:
        - containerPort: 5555
        resources: {}
      restartPolicy: Always
      volumes:
      - name: flower-claim0
        persistentVolumeClaim:
          claimName: flower-claim0
status: {}
