---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    name: mozillians-memcached
  name: mozillians-memcached
  namespace: mozillians-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mozillians-memcached
    spec:
      containers:
      - image: memcached
        name: mozillians-memcached
        ports:
        - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    name: mozillians-memcached
  name: mozillians-memcached
  namespace: mozillians-dev
spec:
  ports:
  - protocol: TCP
    port: 11211
    targetPort: 11211
  selector:
    name: mozillians-memcached
