apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: memcached
  name: memcached
  namespace: mozillians-dev
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: memcached
    spec:
      containers:
      - image: memcached
        name: memcached
        ports:
        - containerPort: 11211
        resources: {}
      restartPolicy: Always
status: {}
