---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    name: mozillians-web
  name: mozillians-web
  namespace: mozillians-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mozillians-web
    spec:
      containers:
      - image: danielhartnell/mozillians:1.0.4
        name: mozillians-web
        ports:
        - containerPort: 8000
        command: ["/code/bin/run-dev.sh"]
        env:
        - name: ALLOWED_HOSTS
          value: "127.0.0.1"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    name: mozillians-web
  name: mozillians-web
  namespace: mozillians-dev
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    name: mozillians-web
